### ISSUE TITLE
Stack trace when getting github event

### ISSUE THREAD

**Issue by nibalizer** [BonnyCI/zuul#1]
When a pull request is opened on a tracked repository we get the following in the logs

```
2016-11-25 04:38:32,956 DEBUG zuul.Scheduler: Adding trigger event: <TriggerEvent pr-reopen BonnyCI/sandbox master 1,a8c9edc8cde65837d5b91953f321fe054470e901>
2016-11-25 04:38:32,956 DEBUG zuul.Scheduler: Done adding trigger event: <TriggerEvent pr-reopen BonnyCI/sandbox master 1,a8c9edc8cde65837d5b91953f321fe054470e901>
2016-11-25 04:38:32,956 DEBUG zuul.Scheduler: Run handler awake
2016-11-25 04:38:32,957 DEBUG zuul.Scheduler: Fetching trigger event
2016-11-25 04:38:32,957 DEBUG zuul.Scheduler: Processing trigger event <TriggerEvent pr-reopen BonnyCI/sandbox master 1,a8c9edc8cde65837d5b91953f321fe054470e901>
2016-11-25 04:38:32,957 ERROR zuul.Scheduler: Exception in run handler:
Traceback (most recent call last):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1019, in run
    self.process_event_queue()
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1066, in process_event_queue
    change = pipeline.source.getChange(event, project)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/source/github.py", line 61, in getChange
    change.files = self.getPullFiles(project, change.number)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/source/github.py", line 91, in getPullFiles
    owner, project = project.name.split('/')
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by nibalizer** [comment]
Fixed by not using quotation marks around the github api token.
